version: '3.8'
services:
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - ./app:/var/www/app
    networks:
      sample-network:

  app-npm-run-dev:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
    container_name: app-npm-run-dev
    volumes:
      - ./app:/var/www/app
    expose:
      - "80"
    environment:
      VIRTUAL_HOST: localhost.app-node.sample.jp
    working_dir: /var/www/app
    command:
      # build:build only(for product), docker:npm run dev on docker
      docker
    networks:
      sample-network:
        aliases:
          - localhost.app-node.sample.jp

  nginx-app:
    image: nginx:latest
    container_name: nginx-app
    expose:
      - "80"
    environment:
      VIRTUAL_HOST: localhost.app.sample.jp
    volumes:
      - ./app:/var/www/app
      - ./docker/app/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      sample-network:
        aliases:
          - localhost.app.sample.jp

  db:
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    image: mysql:latest
    container_name: db
    platform: linux/x86_64
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/env/my.cnf:/etc/mysql/my.cnf
      - ./docker/mysql/data:/var/lib/mysql
    networks:
      sample-network:

  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: nginx-proxy
    ports:
      - '80:80'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./docker/proxy/custom.conf:/etc/nginx/conf.d/custom.conf
    networks:
      sample-network:
        aliases:
          - localhost.proxy.sample.jp

  crm-redis:
    image: redis:5-alpine
    container_name: crm-redis
    expose:
      - "6379"
    ports:
      - "6379:6379"
    environment:
      TZ: "Asia/Tokyo"
    volumes:
      - ./redis:/data
    networks:
      sample-network:

networks:
  sample-network:
    driver: bridge
    internal: false
    name: sample-network